version: '3.8'

services:
  api:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_KEY=dev-api-key
    restart: unless-stopped

volumes:
  node_modules: 